# Generated by Django 4.2.29 on 2026-05-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("college_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=50)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("university", models.CharField(blank=True, max_length=200)),
                ("college_type", models.CharField(blank=True, max_length=100)),
                ("naac_grade", models.CharField(blank=True, max_length=10)),
                ("naac_score", models.FloatField(blank=True, null=True)),
                ("nirf_state_rank", models.IntegerField(blank=True, null=True)),
                ("established_year", models.IntegerField(blank=True, null=True)),
                ("total_seats", models.IntegerField(default=0)),
                ("hostel_available", models.BooleanField(default=False)),
                ("website", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.CharField(blank=True, max_length=200)),
                ("contact_number", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["nirf_state_rank", "naac_grade"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("stream", models.CharField(max_length=50)),
                ("discipline", models.CharField(blank=True, max_length=100)),
                ("degree_type", models.CharField(max_length=50)),
                ("duration_years", models.FloatField(default=3.0)),
                ("min_percentage", models.IntegerField(default=45)),
                ("eligible_streams", models.CharField(blank=True, max_length=200)),
                ("kerala_demand_score", models.IntegerField(default=60)),
                ("avg_salary_kerala", models.CharField(blank=True, max_length=100)),
                ("top_job_roles", models.TextField(blank=True)),
                ("psc_relevant", models.BooleanField(default=False)),
                ("cap_applicable", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="KeralaReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=50, unique=True)),
                ("region", models.CharField(blank=True, max_length=50)),
                (
                    "university_affiliation",
                    models.CharField(blank=True, max_length=500),
                ),
                ("cap_nodal_center", models.CharField(blank=True, max_length=500)),
                ("cap_helpline", models.CharField(blank=True, max_length=100)),
                ("govt_quota_percent", models.IntegerField(default=75)),
                ("mgmt_quota_percent", models.IntegerField(default=25)),
                ("psc_exams", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CareerPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("career_path_name", models.CharField(max_length=200)),
                ("top_job_roles", models.TextField()),
                ("avg_salary_kerala", models.CharField(max_length=100)),
                ("top_employers", models.TextField(blank=True)),
                ("psc_exam_relevant", models.CharField(blank=True, max_length=200)),
                ("gulf_opportunity", models.CharField(blank=True, max_length=50)),
                ("further_studies", models.CharField(blank=True, max_length=200)),
                ("demand_score", models.IntegerField(default=60)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_paths",
                        to="core.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollegeCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_seats", models.IntegerField(default=0)),
                ("govt_quota_seats", models.IntegerField(default=0)),
                ("mgmt_quota_seats", models.IntegerField(default=0)),
                ("cutoff_mark", models.IntegerField(default=0)),
                ("fee_per_year", models.CharField(default="0", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="college_courses",
                        to="core.college",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="college_courses",
                        to="core.course",
                    ),
                ),
            ],
            options={
                "unique_together": {("college", "course")},
            },
        ),
    ]
