# Generated by Django 4.2.29 on 2026-05-01 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collegecourse",
            old_name="cutoff_mark",
            new_name="cutoff_general",
        ),
        migrations.RenameField(
            model_name="collegecourse",
            old_name="total_seats",
            new_name="total_intake",
        ),
        migrations.AddField(
            model_name="college",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="college",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="college_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collegecourse",
            name="academic_year",
            field=models.CharField(default="2024-2025", max_length=20),
        ),
        migrations.AlterField(
            model_name="college",
            name="college_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
