# Generated by Django 4.2.29 on 2026-05-01 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("CarrierApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="is_true",
        ),
        migrations.AddField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.CharField(
                choices=[
                    ("Aptitude", "Aptitude"),
                    ("English", "English"),
                    ("Mathematics", "Mathematics"),
                    ("Logic", "Logical Reasoning"),
                ],
                default="Aptitude",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="marks",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="answer",
            name="answer",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="CarrierApp.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
