# Generated by Django 4.2.29 on 2026-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarrierApp", "0002_remove_answer_is_true_answer_is_correct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="sslc_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="district",
            field=models.CharField(
                choices=[
                    ("Alappuzha", "Alappuzha"),
                    ("Ernakulam", "Ernakulam"),
                    ("Idukki", "Idukki"),
                    ("Kannur", "Kannur"),
                    ("Kasaragod", "Kasaragod"),
                    ("Kollam", "Kollam"),
                    ("Kottayam", "Kottayam"),
                    ("Kozhikode", "Kozhikode"),
                    ("Malappuram", "Malappuram"),
                    ("Palakkad", "Palakkad"),
                    ("Pathanamthitta", "Pathanamthitta"),
                    ("Thiruvananthapuram", "Thiruvananthapuram"),
                    ("Thrissur", "Thrissur"),
                    ("Wayanad", "Wayanad"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="qualification",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="stream_12th",
            field=models.CharField(
                choices=[
                    ("Science", "Science"),
                    ("Commerce", "Commerce"),
                    ("Humanities", "Humanities"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
