# Generated by Django 4.2.29 on 2026-05-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarrierApp", "0003_student_dob_student_sslc_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="interest_keywords",
            field=models.TextField(
                blank=True,
                help_text="Comma separated interests like Coding, Healthcare, Business",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="stream_12th",
            field=models.CharField(
                choices=[
                    ("Science", "Science"),
                    ("Commerce", "Commerce"),
                    ("Arts", "Arts"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
