# Generated by Django 4.2.29 on 2026-05-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarrierApp", "0004_student_interest_keywords_alter_student_stream_12th"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="district",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Alappuzha", "Alappuzha"),
                    ("Ernakulam", "Ernakulam"),
                    ("Idukki", "Idukki"),
                    ("Kannur", "Kannur"),
                    ("Kasaragod", "Kasaragod"),
                    ("Kollam", "Kollam"),
                    ("Kottayam", "Kottayam"),
                    ("Kozhikode", "Kozhikode"),
                    ("Malappuram", "Malappuram"),
                    ("Palakkad", "Palakkad"),
                    ("Pathanamthitta", "Pathanamthitta"),
                    ("Thiruvananthapuram", "Thiruvananthapuram"),
                    ("Thrissur", "Thrissur"),
                    ("Wayanad", "Wayanad"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="place",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="stream_12th",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Science", "Science"),
                    ("Commerce", "Commerce"),
                    ("Arts", "Arts"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
