# Generated by Django 4.2.29 on 2026-05-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarrierApp", "0005_alter_student_district_alter_student_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mark",
            name="ai_report",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mark",
            name="dimensions_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
