# Generated by Django 4.2.29 on 2026-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarrierApp", "0006_mark_ai_report_mark_dimensions_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="mark",
            name="raw_responses",
            field=models.TextField(blank=True, null=True),
        ),
    ]
